### ISSUE TITLE
max-width issue when updating angular?

### ISSUE THREAD

**Issue by lpsBetty** [jacek-pulit/angular-elastic-input#16]
I got a strange problem, when updating from angular 1.4.8 to 1.5.3 the pu-elastic-input has always `max-width: 0px` I changed nothing in the HTML template - 

My temporary CSS fix is this:

````
[pu-elastic-input] {
  max-width: 200px !important;
}
````

**Comment by jacek-pulit** [comment]
Hello @lpsBetty,
Thank you for reporting this issue but I've tried to reproduce it with no result.
I prepared few examples of angular-elastic-input working with angular 1.5.3 here: http://codepen.io/jacek-pulit/pen/NrRKdY?editors=1010
Can you verify if this issue is still valid or prepare real working example of it?

**Comment by meirgottlieb** [comment]
Same problem here. Here is an [example](http://codepen.io/anon/pen/WxEXLO?editors=1010). Look at the "Default" example. I've wrapped it in a `span` tag and now the max-width of the input is 0px.

**Comment by jacek-pulit** [comment]
Thank you @meirgottlieb for this example, finally I was able to debug and solve this issue.
There was a problem when input element was wrapped by inline element (e.g. span).
